#!/bin/bash
set -euo pipefail

WB_PATH=$(dirname "$0")
GIT_WORK_TREE=$($WB_PATH/git-workbench-dir)

if [ -d "$GIT_WORK_TREE" ]; then
  >&2 echo Removing Git repository in $GIT_WORK_TREE
  exec rm -rf $GIT_WORK_TREE
fi
