#!/bin/bash
set -euo pipefail

WB_PATH=$(dirname "$0")

if [[ $# > 0 ]] && [[ -x "$WB_PATH/git-workbench-$1" ]]; then
  COMMAND=$1
  shift
  exec "$WB_PATH/git-workbench-$COMMAND" "$@"
fi

$WB_PATH/git-workbench-init

export GIT_WORK_TREE=$($WB_PATH/git-workbench-dir)
export GIT_DIR=$GIT_WORK_TREE/.git

exec git "$@"
