#!/bin/bash
set -euo pipefail

# https://github.com/bluefeet/git-workbench

WB_PATH=$(dirname "$0")

if [[ $# > 0 ]] && [[ -x "$WB_PATH/git-workbench-$1" ]]; then
    COMMAND=$1
    shift
    exec "$WB_PATH/git-workbench-$COMMAND" "$@"
fi

export GIT_WORK_TREE=$($WB_PATH/git-workbench-dir)
export GIT_DIR=$GIT_WORK_TREE/.git

if [ ! -d "$GIT_WORK_TREE" ]; then
    $WB_PATH/git-workbench-init
fi

exec git "$@"
